apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ouut
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ouut
    app.kubernetes.io/part-of: tkrw-pr712-0075-0001-app
  name: devfile-sample-ouut
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ouut
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ouut
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0001-tenant/tkrw-pr712-0075-0001-app/devfile-sample-ouut@sha256:6bd888a13259111ea6c6d04bc009c81032a649947ccb52d863560a58da1f9f74
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
